api_football:
  base_url: https://api-football-v1.p.rapidapi.com/v3
  key: TON_API_KEY_ICI

odds_api:
  key: "12c1738e94e0ec40c857aea8203ced57"
  base_url: "https://api.the-odds-api.com/v4"
  sport: "soccer_fifa_world_cup"
  regions: "eu"
bankroll:
  initial: 200
blend:
  dc_weight: 0.3
bzzoiro:
  base_url: https://sports.bzzoiro.com/api/v2
  token: 77767139efb5ef981bb229963c8c6e0e89c2b703
leagues:
  friendlies: 31
  world_cup: 27
model:
  decay: 0.001
  friendly_weight: 0.3
  kelly_fraction: 0.14
  max_kelly_bet: 0.021
  min_edge_threshold: 0.07
seasons:
  backtest: 2022
  live: 2026
  training:
  - 2018
  - 2019
  - 2020
  - 2021
  - 2022
telegram:
  chat_id: TON_CHAT_ID_ICI
  token: TON_BOT_TOKEN_ICI
